#ifndef MODBUSCORE_VERSION_CONFIG_H_
#define MODBUSCORE_VERSION_CONFIG_H_

#define MODBUSCORE_MAJOR_VERSION (1)
#define MODBUSCORE_MINOR_VERSION (0)
#define MODBUSCORE_PATCH_VERSION (0)
#define MODBUSCORE_VERSION "1.0.0"

#endif  /* MODBUSCORE_VERSION_CONFIG_H_ */
